import * as ethereumjsWallet from 'ethereumjs-wallet'
const ethSigUtil = require('eth-sig-util')

import * as HashingLogic from '../src/HashingLogic'
import {TAttestationTypeNames} from 'src'

const aliceWallet = ethereumjsWallet.fromPrivateKey(new Buffer('c87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3', 'hex'))
const alicePrivkey = aliceWallet.getPrivateKey()

const bobWallet = ethereumjsWallet.fromPrivateKey(new Buffer('ae6ae8e5ccbfb04590405997ee2d52d2b330726137b875053c36d94e974d162f', 'hex'))

const bobPrivkey = bobWallet.getPrivateKey()
const bobAddress = bobWallet.getAddressString()

const getClaimNode = (dataStr: string, attType: TAttestationTypeNames, provider = 'Bloom', version = '3.0.0') => {
  return {
    data: {
      data: dataStr,
      nonce: HashingLogic.generateNonce(),
      version: version,
    },
    type: {
      type: attType,
      provider: provider,
      nonce: HashingLogic.generateNonce(),
    },
    aux: HashingLogic.generateNonce(),
  }
}

const NDISample = {
  edulevel: {lastupdated: '2019-09-17', code: '3', source: '2', classification: 'C', desc: 'SECONDARY'},
  dialect: {lastupdated: '2019-09-17', code: 'HN', source: '1', classification: 'C', desc: 'HAINANESE'},
  occupation: {lastupdated: '2019-09-17', code: '25140', source: '2', classification: 'C', desc: 'APPLICATIONS/SYSTEMS PROGRAMMER'},
  mobileno: {
    lastupdated: '2019-09-17',
    source: '2',
    classification: 'C',
    areacode: {value: '65'},
    prefix: {value: '+'},
    nbr: {value: '97399245'},
  },
  mailadd: {
    country: {code: 'SG', desc: 'SINGAPORE'},
    unit: {value: '128'},
    street: {value: 'BEDOK NORTH AVENUE 4'},
    lastupdated: '2019-09-17',
    block: {value: '102'},
    source: '2',
    postal: {value: '460102'},
    classification: 'C',
    floor: {value: '9'},
    type: 'SG',
    building: {value: 'PEARL GARDEN'},
  },
  marriedname: {lastupdated: '2019-09-17', source: '1', classification: 'C', value: ''},
  sponsoredchildrenrecords: [
    {
      birthcountry: {code: 'SG', desc: 'SINGAPORE'},
      dialect: {code: 'SG', desc: 'SWISS GERMAN'},
      race: {code: 'MY', desc: 'MALAY'},
      lifestatus: {code: 'A', desc: 'ALIVE'},
      sex: {code: 'M', desc: 'MALE'},
      source: '1',
      residentialstatus: {code: 'P', desc: 'PR'},
      classification: 'C',
      nric: {value: 'T1872646D'},
      hanyupinyinname: {value: 'JERMAINE LIN YONG JIN'},
      hanyupinyinaliasname: {value: 'LIN YONG JIN'},
      marriedname: {value: 'MR LIM YONG JIN'},
      aliasname: {value: 'JERMAINE LIM YONG JIN'},
      nationality: {code: 'GC', desc: 'BRITISH OVERSEAS TERRITORIES CITIZEN'},
      dob: {value: '2018-05-05'},
      name: {value: 'LIM YONG JIN'},
      lastupdated: '2019-09-17',
      scprgrantdate: {value: '2019-01-05'},
      secondaryrace: {code: 'EU', desc: 'EURASIAN'},
    },
  ],
  divorcedate: {lastupdated: '2019-09-17', source: '1', classification: 'C', value: ''},
  marriagecertno: {lastupdated: '2019-09-17', source: '1', classification: 'C', value: '560123'},
  noahistory: {
    noas: [
      {
        amount: {value: 64400},
        trade: {value: 0},
        interest: {value: 0},
        yearofassessment: {value: '2018'},
        taxclearance: {value: 'N'},
        employment: {value: 64400},
        rent: {value: 0},
        category: {value: 'ORIGINAL'},
      },
      {
        amount: {value: 53700},
        trade: {value: 0},
        interest: {value: 0},
        yearofassessment: {value: '2017'},
        taxclearance: {value: 'N'},
        employment: {value: 36112.8},
        rent: {value: 0},
        category: {value: 'ORIGINAL'},
      },
    ],
    lastupdated: '2019-09-17',
    source: '1',
    classification: 'C',
  },
  ownerprivate: {lastupdated: '2019-09-17', source: '1', classification: 'C', value: false},
  cpfemployers: {
    lastupdated: '2019-09-17',
    source: '1',
    history: [
      {month: {value: '2017-10'}, employer: {value: 'CRYSTAL HORSE INVEST PTE LTD'}},
      {month: {value: '2017-11'}, employer: {value: 'CRYSTAL HORSE INVEST PTE LTD'}},
      {month: {value: '2017-12'}, employer: {value: 'CRYSTAL HORSE INVEST PTE LTD'}},
      {month: {value: '2018-01'}, employer: {value: 'CRYSTAL HORSE INVEST PTE LTD'}},
      {month: {value: '2018-02-01'}, employer: {value: 'CRYSTAL HORSE INVEST PTE LTD'}},
      {month: {value: '2018-03-01'}, employer: {value: 'CRYSTAL HORSE INVEST PTE LTD'}},
      {month: {value: '2018-04-01'}, employer: {value: 'CRYSTAL HORSE INVEST PTE LTD'}},
      {month: {value: '2018-05-01'}, employer: {value: 'CRYSTAL HORSE INVEST PTE LTD'}},
      {month: {value: '2018-06-01'}, employer: {value: 'CRYSTAL HORSE INVEST PTE LTD'}},
      {month: {value: '2018-07-01'}, employer: {value: 'CRYSTAL HORSE INVEST PTE LTD'}},
      {month: {value: '2018-08-01'}, employer: {value: 'CRYSTAL HORSE INVEST PTE LTD'}},
      {month: {value: '2018-09-01'}, employer: {value: 'CRYSTAL HORSE INVEST PTE LTD'}},
      {month: {value: '2018-10-01'}, employer: {value: 'CRYSTAL HORSE INVEST PTE LTD'}},
      {month: {value: '2018-11-01'}, employer: {value: 'CRYSTAL HORSE INVEST PTE LTD'}},
      {month: {value: '2018-12-01'}, employer: {value: 'CRYSTAL HORSE INVEST PTE LTD'}},
    ],
    classification: 'C',
  },
  housingtype: {lastupdated: '2019-09-17', code: '', source: '1', classification: 'C', desc: ''},
  passexpirydate: {lastupdated: '2019-09-17', source: '3', classification: 'C', value: ''},
  homeno: {
    lastupdated: '2019-09-17',
    source: '2',
    classification: 'C',
    areacode: {value: '65'},
    prefix: {value: '+'},
    nbr: {value: '69876543'},
  },
  residentialstatus: {lastupdated: '2019-09-17', code: 'C', source: '1', classification: 'C', desc: 'Citizen'},
  cpfbalances: {
    oa: {value: 58839.75},
    ma: {value: 20466},
    lastupdated: '2019-09-17',
    source: '1',
    classification: 'C',
    sa: {value: 15349.5},
    ra: {value: 0},
  },
  passportnumber: {lastupdated: '2019-09-17', source: '1', classification: 'C', value: 'E35463874W'},
  schoolname: {lastupdated: '2019-09-17', code: 'T07GS3203L', source: '2', classification: 'C', desc: 'BUKIT MERAH SECONDARY SCHOOL'},
  hanyupinyinaliasname: {lastupdated: '2019-09-17', source: '1', classification: 'C', value: 'TRICIA TAN XIAO HUI'},
  aliasname: {lastupdated: '2019-09-17', source: '1', classification: 'C', value: 'TRICIA TAN XIAO HUI'},
  passstatus: {lastupdated: '2019-09-17', source: '3', classification: 'C', value: ''},
  nationality: {lastupdated: '2019-09-17', code: 'SG', source: '1', classification: 'C', desc: 'SINGAPORE CITIZEN'},
  dob: {lastupdated: '2019-09-17', source: '1', classification: 'C', value: '1998-06-06'},
  name: {lastupdated: '2019-09-17', source: '1', classification: 'C', value: 'TAN XIAO HUI'},
  noa: {
    amount: {value: 64400},
    trade: {value: 0},
    interest: {value: 0},
    yearofassessment: {value: '2018'},
    taxclearance: {value: 'N'},
    lastupdated: '2019-09-17',
    source: '1',
    employment: {value: 64400},
    classification: 'C',
    rent: {value: 0},
    category: {value: 'ORIGINAL'},
  },
  'noa-basic': {yearofassessment: {value: '2018'}, lastupdated: '2019-09-17', amount: {value: 64400}, source: '1', classification: 'C'},
  passtype: {lastupdated: '2019-09-17', code: '', source: '3', classification: 'C', desc: ''},
  regadd: {
    country: {code: 'SG', desc: 'SINGAPORE'},
    unit: {value: '128'},
    street: {value: 'BEDOK NORTH AVENUE 4'},
    lastupdated: '2019-09-17',
    block: {value: '102'},
    source: '1',
    postal: {value: '460102'},
    classification: 'C',
    floor: {value: '9'},
    type: 'SG',
    building: {value: 'PEARL GARDEN'},
  },
  vehicles: [
    {
      roadtaxexpirydate: {value: '2019-12-12'},
      engineno: {value: 'M13A1837453'},
      attachment3: {value: 'ROOF TENT'},
      effectiveownership: {value: '2013-05-19T12:28:19'},
      scheme: {value: 'ROPC - REVISED OFF-PEAK CAR'},
      powerrate: {value: 1.8},
      source: '1',
      primarycolour: {value: 'BLACK'},
      type: {value: 'Station Wagon/Jeep/Land Rover'},
      vehicleno: {value: 'SDF1235A'},
      coeexpirydate: {value: '2023-05-19'},
      chassisno: {value: 'ZC11S1735800'},
      noxemission: {value: 0.015678},
      model: {value: 'KIA SEDONA'},
      openmarketvalue: {value: 17493.35},
      coemission: {value: 0.135982},
      attachment2: {value: 'SUN ROOF'},
      attachment1: {value: 'BICYCLE CARRIER'},
      make: {value: 'KIA'},
      pmemission: {value: 0.194},
      originalregistrationdate: {value: '2012-08-19'},
      yearofmanufacture: {value: '2013'},
      vpc: {value: ''},
      enginecapacity: {value: 1500},
      classification: 'C',
      nooftransfers: {value: 1},
      propellant: {value: 'Petrol-Electric'},
      co2emission: {value: 155},
      motorno: {value: 'M13A1837453'},
      minimumparfbenefit: {value: 2500},
      thcemission: {value: 0.198765},
      firstregistrationdate: {value: '2013-05-19'},
      lastupdated: '2019-09-17',
      maximumunladenweight: {value: 1800},
      coecategory: {value: 'C - GOODS VEHICLE & BUS'},
      maximumladenweight: {value: 2200},
      secondarycolour: {value: ''},
      iulabelno: {value: '1234567890'},
      quotapremium: {value: 14000},
      status: {code: '2', desc: 'DE-REGISTERED'},
    },
  ],
  billadd: {
    country: {code: 'SG', desc: 'SINGAPORE'},
    unit: {value: '128'},
    street: {value: 'BEDOK NORTH AVENUE 4'},
    lastupdated: '2019-09-17',
    block: {value: '102'},
    source: '2',
    postal: {value: '460102'},
    classification: 'C',
    floor: {value: '9'},
    type: 'SG',
    building: {value: 'PEARL GARDEN'},
  },
  hanyupinyinname: {lastupdated: '2019-09-17', source: '1', classification: 'C', value: 'TAN XIAO HUI'},
  passportexpirydate: {lastupdated: '2019-09-17', source: '1', classification: 'C', value: '2020-01-01'},
  uinfin: {lastupdated: '2019-09-17', source: '1', classification: 'C', value: 'S9812381D'},
  gradyear: {lastupdated: '2019-09-17', source: '2', classification: 'C', value: ''},
  householdincome: {lastupdated: '2019-09-17', high: {value: 4999}, source: '2', classification: 'C', low: {value: 4000}},
  partialuinfin: {lastupdated: '2019-09-17', source: '1', classification: 'C', value: '*****381D'},
  merdekagen: {
    lastupdated: '2019-09-17',
    eligibility: {value: ''},
    quantum: {value: ''},
    source: '1',
    classification: 'C',
    message: {code: '', desc: ''},
  },
  cpfcontributions: {
    lastupdated: '2019-09-17',
    source: '1',
    history: [
      {date: {value: '2017-10-28'}, employer: {value: 'CRYSTAL HORSE INVEST PTE LTD'}, amount: {value: 1425}, month: {value: '2017-10'}},
      {date: {value: '2017-11-28'}, employer: {value: 'CRYSTAL HORSE INVEST PTE LTD'}, amount: {value: 1425}, month: {value: '2017-11'}},
      {date: {value: '2017-12-28'}, employer: {value: 'CRYSTAL HORSE INVEST PTE LTD'}, amount: {value: 2850}, month: {value: '2017-12'}},
      {date: {value: '2018-01-28'}, employer: {value: 'CRYSTAL HORSE INVEST PTE LTD'}, amount: {value: 1425}, month: {value: '2018-01'}},
      {date: {value: '2018-02-28'}, employer: {value: 'CRYSTAL HORSE INVEST PTE LTD'}, amount: {value: 1425}, month: {value: '2018-02'}},
      {date: {value: '2018-03-28'}, employer: {value: 'CRYSTAL HORSE INVEST PTE LTD'}, amount: {value: 1425}, month: {value: '2018-03'}},
      {date: {value: '2018-04-28'}, employer: {value: 'CRYSTAL HORSE INVEST PTE LTD'}, amount: {value: 5700}, month: {value: '2018-04'}},
      {date: {value: '2018-05-28'}, employer: {value: 'CRYSTAL HORSE INVEST PTE LTD'}, amount: {value: 1575}, month: {value: '2018-05'}},
      {date: {value: '2018-06-28'}, employer: {value: 'CRYSTAL HORSE INVEST PTE LTD'}, amount: {value: 1575}, month: {value: '2018-06'}},
      {date: {value: '2018-07-28'}, employer: {value: 'CRYSTAL HORSE INVEST PTE LTD'}, amount: {value: 1575}, month: {value: '2018-07'}},
      {date: {value: '2018-08-28'}, employer: {value: 'CRYSTAL HORSE INVEST PTE LTD'}, amount: {value: 1575}, month: {value: '2018-08'}},
      {date: {value: '2018-09-28'}, employer: {value: 'CRYSTAL HORSE INVEST PTE LTD'}, amount: {value: 1575}, month: {value: '2018-09'}},
      {date: {value: '2018-10-28'}, employer: {value: 'CRYSTAL HORSE INVEST PTE LTD'}, amount: {value: 1575}, month: {value: '2018-10'}},
      {date: {value: '2018-11-28'}, employer: {value: 'CRYSTAL HORSE INVEST PTE LTD'}, amount: {value: 1575}, month: {value: '2018-11'}},
      {date: {value: '2018-12-28'}, employer: {value: 'CRYSTAL HORSE INVEST PTE LTD'}, amount: {value: 3150}, month: {value: '2018-12'}},
    ],
    classification: 'C',
  },
  gstvoucher: {
    gstregular: {value: ''},
    year: {value: ''},
    lastupdated: '2019-09-17',
    exclusion: {value: ''},
    gstmedisave: {value: ''},
    gstspecial: {value: ''},
    source: '1',
    classification: 'C',
    signup: {value: ''},
  },
  email: {lastupdated: '2019-09-17', source: '2', classification: 'C', value: 'myinfotesting@gmail.com'},
  'noahistory-basic': {
    noas: [{yearofassessment: {value: '2018'}, amount: {value: 64400}}, {yearofassessment: {value: '2017'}, amount: {value: 53700}}],
    lastupdated: '2019-09-17',
    source: '1',
    classification: 'C',
  },
  birthcountry: {lastupdated: '2019-09-17', code: 'SG', source: '1', classification: 'C', desc: 'SINGAPORE'},
  race: {lastupdated: '2019-09-17', code: 'CN', source: '1', classification: 'C', desc: 'CHINESE'},
  silversupport: {
    lastupdated: '2019-09-17',
    eligibility: {value: ''},
    amount: {value: ''},
    source: '1',
    classification: 'C',
    year: {value: ''},
  },
  sex: {lastupdated: '2019-09-17', code: 'F', source: '1', classification: 'C', desc: 'FEMALE'},
  countryofmarriage: {lastupdated: '2019-09-17', code: 'SG', source: '1', classification: 'C', desc: 'SINGAPORE'},
  hdbtype: {lastupdated: '2019-09-17', code: '113', source: '1', classification: 'C', desc: '3-ROOM FLAT (HDB)'},
  employmentsector: {lastupdated: '2019-09-17', source: '3', classification: 'C', value: ''},
  marriagedate: {lastupdated: '2019-09-17', source: '1', classification: 'C', value: '2018-03-21'},
  employment: {lastupdated: '2019-09-17', source: '2', classification: 'C', value: 'CRYSTAL HORSE INVEST PTE LTD'},
  hdbownership: [
    {
      termoflease: {value: 99},
      dateofpurchase: {value: '2017-04-21'},
      leasecommencementdate: {value: '2017-04-21'},
      address: {
        country: {code: 'SG', desc: 'SINGAPORE'},
        unit: {value: '128'},
        street: {value: 'BEDOK NORTH AVENUE 4'},
        block: {value: '102'},
        postal: {value: '460102'},
        type: 'SG',
        floor: {value: '9'},
        building: {value: 'PEARL GARDEN'},
      },
      balanceloanrepayment: {years: {value: 20}, months: {value: 2}},
      originalloanrepayment: {value: 25},
      hdbtype: {code: '113', desc: '3-ROOM FLAT (HDB)'},
      source: '1',
      classification: 'C',
      monthlyloaninstalment: {value: 1800},
      outstandingloanbalance: {value: 435600},
      lastupdated: '2019-09-17',
      noofowners: {value: 2},
      dateofownershiptransfer: {value: ''},
      loangranted: {value: 400000},
    },
    {
      termoflease: {value: 99},
      dateofpurchase: {value: '1980-01-05'},
      leasecommencementdate: {value: '1980-06-12'},
      address: {
        country: {code: 'SG', desc: 'SINGAPORE'},
        unit: {value: '1900-01-09'},
        street: {value: 'POKER STREET'},
        block: {value: '123'},
        postal: {value: '000123'},
        type: 'SG',
        floor: {value: '10'},
        building: {value: 'SPADE BUILDING'},
      },
      balanceloanrepayment: {years: {value: 0}, months: {value: 0}},
      originalloanrepayment: {value: 0},
      hdbtype: {code: '118', desc: 'STUDIO APARTMENT (HDB)'},
      source: '1',
      classification: 'C',
      monthlyloaninstalment: {value: 0},
      outstandingloanbalance: {value: 0},
      lastupdated: '2019-09-17',
      noofowners: {value: 2},
      dateofownershiptransfer: {value: ''},
      loangranted: {value: 0},
    },
  ],
  marital: {lastupdated: '2019-09-17', code: '2', source: '1', classification: 'C', desc: 'MARRIED'},
  childrenbirthrecords: [
    {
      dialect: {code: 'TC', desc: 'TEOCHEW'},
      race: {code: 'CN', desc: 'CHINESE'},
      lifestatus: {code: 'A', desc: 'ALIVE'},
      tob: {value: '0933'},
      sex: {code: 'F', desc: 'FEMALE'},
      source: '1',
      classification: 'C',
      birthcertno: {value: 'T1808765Z'},
      hanyupinyinname: {value: 'CHENG YI TING'},
      hanyupinyinaliasname: {value: ''},
      marriedname: {value: ''},
      aliasname: {value: ''},
      dob: {value: '2018-04-13'},
      name: {value: 'TAN YEE TENG'},
      lastupdated: '2019-09-17',
      secondaryrace: {code: '', desc: ''},
    },
  ],
  drivinglicence: {
    revocation: {startdate: {value: ''}, enddate: {value: ''}},
    totaldemeritpoints: {value: 24},
    disqualification: {startdate: {value: ''}, enddate: {value: ''}},
    qdl: {
      expirydate: {value: ''},
      validity: {code: 'V', desc: 'VALID'},
      classes: [
        {class: {value: '2A'}, issuedate: {value: '2018-06-06'}},
        {class: {value: '3A'}, issuedate: {value: '2018-06-06'}},
        {class: {value: '3A'}, issuedate: {value: '2018-06-06'}},
      ],
    },
    lastupdated: '2019-09-17',
    pdl: {expirydate: {value: ''}, validity: {code: '', desc: ''}, classes: []},
    source: '1',
    classification: 'C',
    comstatus: {code: 'N', desc: 'Not Eligible'},
    photocardserialno: {value: '115616'},
    suspension: {startdate: {value: '2019-03-01'}, enddate: {value: '2019-05-23'}},
  },
  secondaryrace: {lastupdated: '2019-09-17', code: '', source: '1', classification: 'C', desc: ''},
}

const personalClaim = getClaimNode(JSON.stringify(NDISample.name), 'full-name', 'NDI')
const addressClaim = getClaimNode(JSON.stringify(NDISample.mailadd), 'address', 'NDI')
const emailClaim = getClaimNode(JSON.stringify(NDISample.email), 'email', 'NDI')
const phoneClaim = getClaimNode(JSON.stringify(NDISample.mobileno), 'phone', 'NDI')
const incomeClaim = getClaimNode(JSON.stringify(NDISample.householdincome), 'income', 'NDI')

const contractAddress = '0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC'

const issuanceDate = '2018-02-01T00:00:00.000Z'
const expirationDate = '2020-02-01T00:00:00.000Z'

const merkleTreeComponents = HashingLogic.getSignedMerkleTreeComponents(
  [personalClaim, addressClaim, emailClaim, phoneClaim, incomeClaim],
  issuanceDate,
  expirationDate,
  alicePrivkey,
)
const requestNonce = HashingLogic.generateNonce()

const bobSubjectSig = ethSigUtil.signTypedData(bobPrivkey, {
  data: HashingLogic.getAttestationAgreement(contractAddress, 1, merkleTreeComponents.layer2Hash, requestNonce),
})

const batchMerkleTreeComponents = HashingLogic.getSignedBatchMerkleTreeComponents(
  merkleTreeComponents,
  contractAddress,
  bobSubjectSig,
  bobAddress,
  requestNonce,
  alicePrivkey,
)

test('HashingLogic.hashMessage', () => {
  console.log(JSON.stringify(batchMerkleTreeComponents))
  expect(true)
})
